language: python

services:
  - docker

before_install:
  - docker build -t tagnumelite/blender:nightly .

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push tagnumelite/blender:nightly
  - echo "$GITHUB_PASSWORD" | docker login docker.pkg.github.com -u TagnumElite --password-stdin
  - docker tag tagnumelite/blender:nightly docker.pkg.github.com/tagnumelite/blender-docker/blender:nightly
  - docker push docker.pkg.github.com/tagnumelite/blender-docker/blender:nightly

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $DISCORD_WEBHOOK_URL

after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $DISCORD_WEBHOOK_URL
