language: python

services:
  - docker

before_install:
  - docker build -t tagnumelite/blender:nightly .

script:
  - docker tag tagnumelite/blender:nightly
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push tagnumelite/blender:nightly
  - echo "$GITHUB_PASSWORD" | docker login docker.pkg.github.com --u TagnumElite --password-stdin
  - docker push docker.pkg.github.com/TagnumElite/blender-docker/blender:nightly
